package sap_api_output_formatter

type FunctionalLocation struct {
	ConnectionKey      string `json:"connection_key"`
	Result             bool   `json:"result"`
	RedisKey           string `json:"redis_key"`
	Filepath           string `json:"filepath"`
	APISchema          string `json:"api_schema"`
	FunctionalLocation string `json:"functional_location"`
	Deleted            bool   `json:"deleted"`
}

type Header struct {
	FunctionalLocation             string      `json:"FunctionalLocation"`
	FunctionalLocationLabelName    string      `json:"FunctionalLocationLabelName"`
	FunctionalLocationName         string      `json:"FunctionalLocationName"`
	FuncLocationStructure          string      `json:"FuncLocationStructure"`
	FunctionalLocationCategory     string      `json:"FunctionalLocationCategory"`
	SuperiorFunctionalLocation     string      `json:"SuperiorFunctionalLocation"`
	SuperiorFuncnlLocLabelName     string      `json:"SuperiorFuncnlLocLabelName"`
	TechnicalObjectType            string      `json:"TechnicalObjectType"`
	GrossWeight                    string      `json:"GrossWeight"`
	GrossWeightUnit                string      `json:"GrossWeightUnit"`
	OperationStartDate             string      `json:"OperationStartDate"`
	InventoryNumber                string      `json:"InventoryNumber"`
	AcquisitionValue               string      `json:"AcquisitionValue"`
	Currency                       string      `json:"Currency"`
	AcquisitionDate                string      `json:"AcquisitionDate"`
	AssetManufacturerName          string      `json:"AssetManufacturerName"`
	ManufacturerPartNmbr           string      `json:"ManufacturerPartNmbr"`
	ManufacturerCountry            string      `json:"ManufacturerCountry"`
	ManufacturerPartTypeName       string      `json:"ManufacturerPartTypeName"`
	ConstructionMonth              string      `json:"ConstructionMonth"`
	ConstructionYear               string      `json:"ConstructionYear"`
	ManufacturerSerialNumber       string      `json:"ManufacturerSerialNumber"`
	MaintenancePlant               string      `json:"MaintenancePlant"`
	AssetLocation                  string      `json:"AssetLocation"`
	AssetRoom                      string      `json:"AssetRoom"`
	PlantSection                   string      `json:"PlantSection"`
	WorkCenter                     string      `json:"WorkCenter"`
	WorkCenterInternalID           string      `json:"WorkCenterInternalID"`
	WorkCenterPlant                string      `json:"WorkCenterPlant"`
	ABCIndicator                   string      `json:"ABCIndicator"`
	MaintObjectFreeDefinedAttrib   string      `json:"MaintObjectFreeDefinedAttrib"`
	FormOfAddress                  string      `json:"FormOfAddress"`
	BusinessPartnerName1           string      `json:"BusinessPartnerName1"`
	BusinessPartnerName2           string      `json:"BusinessPartnerName2"`
	CityName                       string      `json:"CityName"`
	PostalCode                     string      `json:"PostalCode"`
	StreetName                     string      `json:"StreetName"`
	Region                         string      `json:"Region"`
	Country                        string      `json:"Country"`
	PhoneNumber                    string      `json:"PhoneNumber"`
	FaxNumber                      string      `json:"FaxNumber"`
	CompanyCode                    string      `json:"CompanyCode"`
	BusinessArea                   string      `json:"BusinessArea"`
	MasterFixedAsset               string      `json:"MasterFixedAsset"`
	FixedAsset                     string      `json:"FixedAsset"`
	CostCenter                     string      `json:"CostCenter"`
	ControllingArea                string      `json:"ControllingArea"`
	WBSElementExternalID           string      `json:"WBSElementExternalID"`
	SettlementOrder                string      `json:"SettlementOrder"`
	ConstructionMaterial           string      `json:"ConstructionMaterial"`
	MaintenancePlannerGroup        string      `json:"MaintenancePlannerGroup"`
	MaintenancePlanningPlant       string      `json:"MaintenancePlanningPlant"`
	MainWorkCenterPlant            string      `json:"MainWorkCenterPlant"`
	MainWorkCenter                 string      `json:"MainWorkCenter"`
	MainWorkCenterInternalID       string      `json:"MainWorkCenterInternalID"`
	CatalogProfile                 string      `json:"CatalogProfile"`
	EquipmentInstallationIsAllowed bool        `json:"EquipmentInstallationIsAllowed"`
	OnePieceOfEquipmentIsAllowed   bool        `json:"OnePieceOfEquipmentIsAllowed"`
	SalesOrganization              string      `json:"SalesOrganization"`
	DistributionChannel            string      `json:"DistributionChannel"`
	SalesOffice                    string      `json:"SalesOffice"`
	OrganizationDivision           string      `json:"OrganizationDivision"`
	SalesGroup                     string      `json:"SalesGroup"`
	FunctionalLocationHasEquipment string      `json:"FunctionalLocationHasEquipment"`
	FuncnlLocHasSubOrdinateFuncLoc string      `json:"FuncnlLocHasSubOrdinateFuncLoc"`
	LastChangeDateTime             string      `json:"LastChangeDateTime"`
	FuncnlLocIsMarkedForDeletion   bool        `json:"FuncnlLocIsMarkedForDeletion"`
	FuncnlLocIsDeleted             bool        `json:"FuncnlLocIsDeleted"`
	FunctionalLocationIsActive     bool        `json:"FunctionalLocationIsActive"`
	FuncnlLocIsDeactivated         bool        `json:"FuncnlLocIsDeactivated"`
	CreationDate                   string      `json:"CreationDate"`
}
