package sap_api_input_reader

type EC_MC struct {
	ConnectionKey string `json:"connection_key"`
	Result        bool   `json:"result"`
	RedisKey      string `json:"redis_key"`
	Filepath      string `json:"filepath"`
	Document      struct {
		DocumentNo     string `json:"document_no"`
		DeliverTo      string `json:"deliver_to"`
		Quantity       string `json:"quantity"`
		PickedQuantity string `json:"picked_quantity"`
		Price          string `json:"price"`
		Batch          string `json:"batch"`
	} `json:"document"`
	ProductionOrder struct {
		DocumentNo           string `json:"document_no"`
		Status               string `json:"status"`
		DeliverTo            string `json:"deliver_to"`
		Quantity             string `json:"quantity"`
		CompletedQuantity    string `json:"completed_quantity"`
		PlannedStartDate     string `json:"planned_start_date"`
		PlannedValidatedDate string `json:"planned_validated_date"`
		ActualStartDate      string `json:"actual_start_date"`
		ActualValidatedDate  string `json:"actual_validated_date"`
		Batch                string `json:"batch"`
		Work                 struct {
			WorkNo                   string `json:"work_no"`
			Quantity                 string `json:"quantity"`
			CompletedQuantity        string `json:"completed_quantity"`
			ErroredQuantity          string `json:"errored_quantity"`
			Component                string `json:"component"`
			PlannedComponentQuantity string `json:"planned_component_quantity"`
			PlannedStartDate         string `json:"planned_start_date"`
			PlannedStartTime         string `json:"planned_start_time"`
			PlannedValidatedDate     string `json:"planned_validated_date"`
			PlannedValidatedTime     string `json:"planned_validated_time"`
			ActualStartDate          string `json:"actual_start_date"`
			ActualStartTime          string `json:"actual_start_time"`
			ActualValidatedDate      string `json:"actual_validated_date"`
			ActualValidatedTime      string `json:"actual_validated_time"`
		} `json:"work"`
	} `json:"production_order"`
	APISchema      string `json:"api_schema"`
	MaterialCode   string `json:"material_code"`
	Plant_Supplier string `json:"plant/supplier"`
	Stock          string `json:"stock"`
	DocumentType   string `json:"document_type"`
	DocumentNo     string `json:"document_no"`
	PlannedDate    string `json:"planned_date"`
	ValidatedDate  string `json:"validated_date"`
	Deleted        bool   `json:"deleted"`
}

type SDC struct {
	ConnectionKey      string `json:"connection_key"`
	Result             bool   `json:"result"`
	RedisKey           string `json:"redis_key"`
	Filepath           string `json:"filepath"`
	FunctionalLocation struct {
		FunctionalLocation             string      `json:"FunctionalLocation"`
		FunctionalLocationLabelName    string      `json:"FunctionalLocationLabelName"`
		FunctionalLocationName         string      `json:"FunctionalLocationName"`
		FuncLocationStructure          string      `json:"FuncLocationStructure"`
		FunctionalLocationCategory     string      `json:"FunctionalLocationCategory"`
		SuperiorFunctionalLocation     string      `json:"SuperiorFunctionalLocation"`
		SuperiorFuncnlLocLabelName     string      `json:"SuperiorFuncnlLocLabelName"`
		TechnicalObjectType            string      `json:"TechnicalObjectType"`
		GrossWeight                    string      `json:"GrossWeight"`
		GrossWeightUnit                string      `json:"GrossWeightUnit"`
		OperationStartDate             string      `json:"OperationStartDate"`
		InventoryNumber                string      `json:"InventoryNumber"`
		AcquisitionValue               string      `json:"AcquisitionValue"`
		Currency                       string      `json:"Currency"`
		AcquisitionDate                string      `json:"AcquisitionDate"`
		AssetManufacturerName          string      `json:"AssetManufacturerName"`
		ManufacturerPartNmbr           string      `json:"ManufacturerPartNmbr"`
		ManufacturerCountry            string      `json:"ManufacturerCountry"`
		ManufacturerPartTypeName       string      `json:"ManufacturerPartTypeName"`
		ConstructionMonth              string      `json:"ConstructionMonth"`
		ConstructionYear               string      `json:"ConstructionYear"`
		ManufacturerSerialNumber       string      `json:"ManufacturerSerialNumber"`
		MaintenancePlant               string      `json:"MaintenancePlant"`
		AssetLocation                  string      `json:"AssetLocation"`
		AssetRoom                      string      `json:"AssetRoom"`
		PlantSection                   string      `json:"PlantSection"`
		WorkCenter                     string      `json:"WorkCenter"`
		WorkCenterInternalID           string      `json:"WorkCenterInternalID"`
		WorkCenterPlant                string      `json:"WorkCenterPlant"`
		ABCIndicator                   string      `json:"ABCIndicator"`
		MaintObjectFreeDefinedAttrib   string      `json:"MaintObjectFreeDefinedAttrib"`
		FormOfAddress                  string      `json:"FormOfAddress"`
		BusinessPartnerName1           string      `json:"BusinessPartnerName1"`
		BusinessPartnerName2           string      `json:"BusinessPartnerName2"`
		CityName                       string      `json:"CityName"`
		PostalCode                     string      `json:"PostalCode"`
		StreetName                     string      `json:"StreetName"`
		Region                         string      `json:"Region"`
		Country                        string      `json:"Country"`
		PhoneNumber                    string      `json:"PhoneNumber"`
		FaxNumber                      string      `json:"FaxNumber"`
		CompanyCode                    string      `json:"CompanyCode"`
		BusinessArea                   string      `json:"BusinessArea"`
		MasterFixedAsset               string      `json:"MasterFixedAsset"`
		FixedAsset                     string      `json:"FixedAsset"`
		CostCenter                     string      `json:"CostCenter"`
		ControllingArea                string      `json:"ControllingArea"`
		WBSElementExternalID           string      `json:"WBSElementExternalID"`
		SettlementOrder                string      `json:"SettlementOrder"`
		ConstructionMaterial           string      `json:"ConstructionMaterial"`
		MaintenancePlannerGroup        string      `json:"MaintenancePlannerGroup"`
		MaintenancePlanningPlant       string      `json:"MaintenancePlanningPlant"`
		MainWorkCenterPlant            string      `json:"MainWorkCenterPlant"`
		MainWorkCenter                 string      `json:"MainWorkCenter"`
		MainWorkCenterInternalID       string      `json:"MainWorkCenterInternalID"`
		CatalogProfile                 string      `json:"CatalogProfile"`
		EquipmentInstallationIsAllowed bool        `json:"EquipmentInstallationIsAllowed"`
		OnePieceOfEquipmentIsAllowed   bool        `json:"OnePieceOfEquipmentIsAllowed"`
		SalesOrganization              string      `json:"SalesOrganization"`
		DistributionChannel            string      `json:"DistributionChannel"`
		SalesOffice                    string      `json:"SalesOffice"`
		OrganizationDivision           string      `json:"OrganizationDivision"`
		SalesGroup                     string      `json:"SalesGroup"`
		FunctionalLocationHasEquipment string      `json:"FunctionalLocationHasEquipment"`
		FuncnlLocHasSubOrdinateFuncLoc string      `json:"FuncnlLocHasSubOrdinateFuncLoc"`
		LastChangeDateTime             string      `json:"LastChangeDateTime"`
		FuncnlLocIsMarkedForDeletion   bool        `json:"FuncnlLocIsMarkedForDeletion"`
		FuncnlLocIsDeleted             bool        `json:"FuncnlLocIsDeleted"`
		FunctionalLocationIsActive     bool        `json:"FunctionalLocationIsActive"`
		FuncnlLocIsDeactivated         bool        `json:"FuncnlLocIsDeactivated"`
		CreationDate                   string      `json:"CreationDate"`
	} `json:"FunctionalLocation"`
	APISchema              string   `json:"api_schema"`
	Accepter               []string `json:"accepter"`
	FunctionalLocationCode string   `json:"functional_location_code"`
	Deleted                bool     `json:"deleted"`
}
